### ISSUE TITLE
Messenger documentation bug

### ISSUE THREAD

**Issue by vraffy** [restfb/restfb#592]
In the "MESSENGER PLATFORM" section of your [documentation page](http://restfb.com/documentation/) I have found some not working snippet codes.

In the "CREATING A IMAGE MESSAGE" paragraph, I think it should instead be:
`MediaAttachment image = new MediaAttachment(IMAGE, "http://example.com/testimage.jpg");
Message imageMessage = new Message(image);`

In the "USE THE BUTTON TEMPLATE",  it should be 
`payload.addButton(webButton);` 
instead of 
`payload.add(webButton);`

Moreover, if I try to use this code, I receive an error message from Facebook:
`OAuthException: (#100) The parameter text is required (code 100, subcode null)`

Similar issue with the "USE THE GENERIC TEMPLATE" paragraph:
`firstBubble.addButton(webButton);`
...
`payload.addBubble(firstBubble);`

Moreover, if I try to use this code, the user receives only the first bubble.
The second one does not arrive. If I comment the first one, the user gets the second one.
So it looks like it is not an issue with the second bubble itself, but in sending more than one bubble.

**Comment by nbartels** [comment]
Okay, so we have a lot things here 😄 

First you found a bug in the `ButtonTemplatePayload`, because the `text`-field is not required in the current implementation. I changed this and commit the change soon.

In the documentation I changed this:
* The `MediaAttachment` is changed. 
* `add` method is `addButton` now

I cannot reproduce the multi-bubble issue ... perhaps you can check this again?

**Comment by nbartels** [comment]
@vraffy I close this issue here. If you have still the multi bubble problem please open another issue and provide some example code. So we can move forward with this as the bug is solved and the documentation is added and will be published with the next version.

**Comment by vraffy** [comment]
I can confirm I still have the multi bubble issue.
As per your request, I am going to open a new issue and attach the example code.
In the meanwhile, thank you very much for your prompt response :)
